// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GymCQuickType;
//
//    var pokeGymCards = PokeGymCards.FromJson(jsonString);

namespace GymCQuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PokeGymCards
    {
        [JsonProperty("cards")]
        public List<Card> Cards { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("imageUrl")]
        public Uri ImageUrl { get; set; }

        [JsonProperty("imageUrlHiRes")]
        public Uri ImageUrlHiRes { get; set; }

        [JsonProperty("supertype")]
        public Supertype Supertype { get; set; }

        [JsonProperty("subtype")]
        public Subtype Subtype { get; set; }

        [JsonProperty("number")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Number { get; set; }

        [JsonProperty("artist")]
        public Artist Artist { get; set; }

        [JsonProperty("rarity")]
        public Rarity Rarity { get; set; }

        [JsonProperty("series")]
        public Series Series { get; set; }

        [JsonProperty("set")]
        public Set Set { get; set; }

        [JsonProperty("setCode")]
        public SetCode SetCode { get; set; }

        [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Text { get; set; }

        [JsonProperty("nationalPokedexNumber", NullValueHandling = NullValueHandling.Ignore)]
        public long? NationalPokedexNumber { get; set; }

        [JsonProperty("types", NullValueHandling = NullValueHandling.Ignore)]
        public List<RetreatCost> Types { get; set; }

        [JsonProperty("hp", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? Hp { get; set; }

        [JsonProperty("retreatCost", NullValueHandling = NullValueHandling.Ignore)]
        public List<RetreatCost> RetreatCost { get; set; }

        [JsonProperty("convertedRetreatCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? ConvertedRetreatCost { get; set; }

        [JsonProperty("attacks", NullValueHandling = NullValueHandling.Ignore)]
        public List<Attack> Attacks { get; set; }

        [JsonProperty("weaknesses", NullValueHandling = NullValueHandling.Ignore)]
        public List<Resistance> Weaknesses { get; set; }

        [JsonProperty("evolvesFrom", NullValueHandling = NullValueHandling.Ignore)]
        public string EvolvesFrom { get; set; }

        [JsonProperty("resistances", NullValueHandling = NullValueHandling.Ignore)]
        public List<Resistance> Resistances { get; set; }

        [JsonProperty("ability", NullValueHandling = NullValueHandling.Ignore)]
        public Ability Ability { get; set; }
    }

    public partial class Ability
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class Attack
    {
        [JsonProperty("cost")]
        public List<RetreatCost> Cost { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("damage")]
        public string Damage { get; set; }

        [JsonProperty("convertedEnergyCost")]
        public long ConvertedEnergyCost { get; set; }
    }

    public partial class Resistance
    {
        [JsonProperty("type")]
        public RetreatCost Type { get; set; }

        [JsonProperty("value")]
        public ValueUnion Value { get; set; }
    }

    public enum TypeEnum { PokémonPower };

    public enum Artist { AtsukoNishida, HikaruKoike, KeijiKinebuchi, KenSugimori, ShinIchiYoshida, SumiyoshiKizuki };

    public enum RetreatCost { Colorless, Fighting, Fire, Grass, Lightning, Psychic, Water };

    public enum Rarity { Common, Rare, Uncommon };

    public enum ValueEnum { The2 };

    public enum Series { Gym };

    public enum Set { GymChallenge };

    public enum SetCode { Gym2 };

    public enum Subtype { Basic, Empty, Stage1, Stage2 };

    public enum Supertype { Energy, Pokémon, Trainer };

    public partial struct ValueUnion
    {
        public ValueEnum? Enum;
        public long? Integer;

        public static implicit operator ValueUnion(ValueEnum Enum) => new ValueUnion { Enum = Enum };
        public static implicit operator ValueUnion(long Integer) => new ValueUnion { Integer = Integer };
    }

    public partial class PokeGymCards
    {
        public static PokeGymCards FromJson(string json) => JsonConvert.DeserializeObject<PokeGymCards>(json, GymCQuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this PokeGymCards self) => JsonConvert.SerializeObject(self, GymCQuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                TypeEnumConverter.Singleton,
                ArtistConverter.Singleton,
                RetreatCostConverter.Singleton,
                RarityConverter.Singleton,
                ValueUnionConverter.Singleton,
                ValueEnumConverter.Singleton,
                SeriesConverter.Singleton,
                SetConverter.Singleton,
                SetCodeConverter.Singleton,
                SubtypeConverter.Singleton,
                SupertypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "Pokémon Power")
            {
                return TypeEnum.PokémonPower;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            if (value == TypeEnum.PokémonPower)
            {
                serializer.Serialize(writer, "Pokémon Power");
                return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class ArtistConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Artist) || t == typeof(Artist?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Atsuko Nishida":
                    return Artist.AtsukoNishida;
                case "Hikaru Koike":
                    return Artist.HikaruKoike;
                case "Keiji Kinebuchi":
                    return Artist.KeijiKinebuchi;
                case "Ken Sugimori":
                    return Artist.KenSugimori;
                case "Shin-ichi Yoshida":
                    return Artist.ShinIchiYoshida;
                case "Sumiyoshi Kizuki":
                    return Artist.SumiyoshiKizuki;
            }
            throw new Exception("Cannot unmarshal type Artist");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Artist)untypedValue;
            switch (value)
            {
                case Artist.AtsukoNishida:
                    serializer.Serialize(writer, "Atsuko Nishida");
                    return;
                case Artist.HikaruKoike:
                    serializer.Serialize(writer, "Hikaru Koike");
                    return;
                case Artist.KeijiKinebuchi:
                    serializer.Serialize(writer, "Keiji Kinebuchi");
                    return;
                case Artist.KenSugimori:
                    serializer.Serialize(writer, "Ken Sugimori");
                    return;
                case Artist.ShinIchiYoshida:
                    serializer.Serialize(writer, "Shin-ichi Yoshida");
                    return;
                case Artist.SumiyoshiKizuki:
                    serializer.Serialize(writer, "Sumiyoshi Kizuki");
                    return;
            }
            throw new Exception("Cannot marshal type Artist");
        }

        public static readonly ArtistConverter Singleton = new ArtistConverter();
    }

    internal class RetreatCostConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(RetreatCost) || t == typeof(RetreatCost?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Colorless":
                    return RetreatCost.Colorless;
                case "Fighting":
                    return RetreatCost.Fighting;
                case "Fire":
                    return RetreatCost.Fire;
                case "Grass":
                    return RetreatCost.Grass;
                case "Lightning":
                    return RetreatCost.Lightning;
                case "Psychic":
                    return RetreatCost.Psychic;
                case "Water":
                    return RetreatCost.Water;
            }
            throw new Exception("Cannot unmarshal type RetreatCost");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (RetreatCost)untypedValue;
            switch (value)
            {
                case RetreatCost.Colorless:
                    serializer.Serialize(writer, "Colorless");
                    return;
                case RetreatCost.Fighting:
                    serializer.Serialize(writer, "Fighting");
                    return;
                case RetreatCost.Fire:
                    serializer.Serialize(writer, "Fire");
                    return;
                case RetreatCost.Grass:
                    serializer.Serialize(writer, "Grass");
                    return;
                case RetreatCost.Lightning:
                    serializer.Serialize(writer, "Lightning");
                    return;
                case RetreatCost.Psychic:
                    serializer.Serialize(writer, "Psychic");
                    return;
                case RetreatCost.Water:
                    serializer.Serialize(writer, "Water");
                    return;
            }
            throw new Exception("Cannot marshal type RetreatCost");
        }

        public static readonly RetreatCostConverter Singleton = new RetreatCostConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class RarityConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Rarity) || t == typeof(Rarity?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Common":
                    return Rarity.Common;
                case "Rare":
                    return Rarity.Rare;
                case "Uncommon":
                    return Rarity.Uncommon;
            }
            throw new Exception("Cannot unmarshal type Rarity");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Rarity)untypedValue;
            switch (value)
            {
                case Rarity.Common:
                    serializer.Serialize(writer, "Common");
                    return;
                case Rarity.Rare:
                    serializer.Serialize(writer, "Rare");
                    return;
                case Rarity.Uncommon:
                    serializer.Serialize(writer, "Uncommon");
                    return;
            }
            throw new Exception("Cannot marshal type Rarity");
        }

        public static readonly RarityConverter Singleton = new RarityConverter();
    }

    internal class ValueUnionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ValueUnion) || t == typeof(ValueUnion?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    if (stringValue == "×2")
                    {
                        return new ValueUnion { Enum = ValueEnum.The2 };
                    }
                    long l;
                    if (Int64.TryParse(stringValue, out l))
                    {
                        return new ValueUnion { Integer = l };
                    }
                    break;
            }
            throw new Exception("Cannot unmarshal type ValueUnion");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (ValueUnion)untypedValue;
            if (value.Enum != null)
            {
                if (value.Enum == ValueEnum.The2)
                {
                    serializer.Serialize(writer, "×2");
                    return;
                }
            }
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value.ToString());
                return;
            }
            throw new Exception("Cannot marshal type ValueUnion");
        }

        public static readonly ValueUnionConverter Singleton = new ValueUnionConverter();
    }

    internal class ValueEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ValueEnum) || t == typeof(ValueEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "×2")
            {
                return ValueEnum.The2;
            }
            throw new Exception("Cannot unmarshal type ValueEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ValueEnum)untypedValue;
            if (value == ValueEnum.The2)
            {
                serializer.Serialize(writer, "×2");
                return;
            }
            throw new Exception("Cannot marshal type ValueEnum");
        }

        public static readonly ValueEnumConverter Singleton = new ValueEnumConverter();
    }

    internal class SeriesConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Series) || t == typeof(Series?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "Gym")
            {
                return Series.Gym;
            }
            throw new Exception("Cannot unmarshal type Series");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Series)untypedValue;
            if (value == Series.Gym)
            {
                serializer.Serialize(writer, "Gym");
                return;
            }
            throw new Exception("Cannot marshal type Series");
        }

        public static readonly SeriesConverter Singleton = new SeriesConverter();
    }

    internal class SetConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Set) || t == typeof(Set?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "Gym Challenge")
            {
                return Set.GymChallenge;
            }
            throw new Exception("Cannot unmarshal type Set");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Set)untypedValue;
            if (value == Set.GymChallenge)
            {
                serializer.Serialize(writer, "Gym Challenge");
                return;
            }
            throw new Exception("Cannot marshal type Set");
        }

        public static readonly SetConverter Singleton = new SetConverter();
    }

    internal class SetCodeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(SetCode) || t == typeof(SetCode?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "gym2")
            {
                return SetCode.Gym2;
            }
            throw new Exception("Cannot unmarshal type SetCode");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (SetCode)untypedValue;
            if (value == SetCode.Gym2)
            {
                serializer.Serialize(writer, "gym2");
                return;
            }
            throw new Exception("Cannot marshal type SetCode");
        }

        public static readonly SetCodeConverter Singleton = new SetCodeConverter();
    }

    internal class SubtypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Subtype) || t == typeof(Subtype?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "":
                    return Subtype.Empty;
                case "Basic":
                    return Subtype.Basic;
                case "Stage 1":
                    return Subtype.Stage1;
                case "Stage 2":
                    return Subtype.Stage2;
            }
            throw new Exception("Cannot unmarshal type Subtype");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Subtype)untypedValue;
            switch (value)
            {
                case Subtype.Empty:
                    serializer.Serialize(writer, "");
                    return;
                case Subtype.Basic:
                    serializer.Serialize(writer, "Basic");
                    return;
                case Subtype.Stage1:
                    serializer.Serialize(writer, "Stage 1");
                    return;
                case Subtype.Stage2:
                    serializer.Serialize(writer, "Stage 2");
                    return;
            }
            throw new Exception("Cannot marshal type Subtype");
        }

        public static readonly SubtypeConverter Singleton = new SubtypeConverter();
    }

    internal class SupertypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Supertype) || t == typeof(Supertype?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Energy":
                    return Supertype.Energy;
                case "Pokémon":
                    return Supertype.Pokémon;
                case "Trainer":
                    return Supertype.Trainer;
            }
            throw new Exception("Cannot unmarshal type Supertype");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Supertype)untypedValue;
            switch (value)
            {
                case Supertype.Energy:
                    serializer.Serialize(writer, "Energy");
                    return;
                case Supertype.Pokémon:
                    serializer.Serialize(writer, "Pokémon");
                    return;
                case Supertype.Trainer:
                    serializer.Serialize(writer, "Trainer");
                    return;
            }
            throw new Exception("Cannot marshal type Supertype");
        }

        public static readonly SupertypeConverter Singleton = new SupertypeConverter();
    }
}
